### PR TITLE
2024: Add chapter on single-line `where` clauses

### PR DESCRIPTION
**Pull request by joshtriplett**

### CODE REVIEW

**Review by traviscross — APPROVED** [review]

**Comment by ehuss** [comment]
This formatting doesn't seem to actually work for me. I have `rustfmt 1.8.0-nightly (c44b3d50fe 2024-12-03)`.

Can you say more about how to get this formatting to work?

**Comment by traviscross** [comment]
This one is still marked `impl-incomplete` on the tracking issue.  Maybe it doesn't.

**Comment by ytmimi** [comment]
To the best of my knowledge this has't been implemented yet, and I don't think there's an open PR for this on the rustfmt side. @calebcartwright, please correct me if I'm wrong. Also, are these rules limited to type aliases / associated types or are they meant to apply to all `where clauses`?

**Comment by traviscross** [comment]
Associated types and associated function or method declarations with no default body.

**Pull request merged**
