### PR TITLE
Revert "2024: Assignment operator RHS indentation"

### PR DESCRIPTION
**Pull request by ehuss**
Reverts rust-lang/edition-guide#341. This isn't implemented. If and when it is ready, this can be added back in.

Tracking:

- https://github.com/rust-lang/rust/issues/132380

### CODE REVIEW

**Comment by traviscross** [comment]
cc @calebcartwright @ytmimi

Do we think this is going to happen in time for the edition?

**Comment by ytmimi** [comment]
I believe so. We've got https://github.com/rust-lang/rustfmt/pull/6305 already open, and with the scope of this reduced to just assignments I think that PR is just about ready to go. I'll review it again this week.

**Comment by calebcartwright** [comment]
> I believe so. We've got [rust-lang/rustfmt#6305](https://github.com/rust-lang/rustfmt/pull/6305) already open, and with the scope of this reduced to just assignments I think that PR is just about ready to go. I'll review it again this week.

i've also got a different version of this that's implemented and ready, just need to get the pr up

**Comment by ytmimi** [comment]
> i've also got a different version of this that's implemented and ready, just need to get the pr up

In that case I'll hold off on reviewing https://github.com/rust-lang/rustfmt/pull/6305 and wait till you open your PR.

**Pull request merged**
