### PR TITLE
Revert "2024: Add chapter on single-line `where` clauses"

### PR DESCRIPTION
**Pull request by ehuss**
Reverts rust-lang/edition-guide#340  This isn't implemented. If and when it is ready, this can be added back in.

Tracking:

- https://github.com/rust-lang/rust/issues/132381

### CODE REVIEW

**Comment by traviscross** [comment]
cc @calebcartwright @ytmimi

Do we think this is going to happen in time for the edition?

**Comment by ytmimi** [comment]
I'm not so sure about this one. To the best of my knowledge we haven't started implementing this.

**Comment by traviscross** [comment]
@rust-lang/style: Heads-up this item is at risk.  If this item will not make it, then we will of course revert this chapter, and we'll also want to revert the change to the style guide ahead of the branch for Rust 1.85:

https://github.com/rust-lang/rust/pull/119515

**Comment by calebcartwright** [comment]
> I'm not so sure about this one. To the best of my knowledge we haven't started implementing this.

it's implemented with tests, just need to get the PR up

**Comment by ytmimi** [comment]
> > I'm not so sure about this one. To the best of my knowledge we haven't started implementing this.
> 
> it's implemented with tests, just need to get the PR up

Oh that's awesome! I'm ready to review whenever you can open the PR.

**Comment by traviscross** [comment]
This item is not going to make Rust 2024, so we're going to land this revert.

**Pull request merged**
